language: go

go:
  - "1.9"
  - master

notifications:
  email:
    recepients:
    - muhammad@dispatchlabs.io
    - nicolae@dispatchlabs.io
    on_success: always
    on_failure: always
script:
  - go build
