// Code generated by protoc-gen-go. DO NOT EDIT.
// source: disgover.proto

package disgover

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_disgover_c7822d8cb2ad3fb3, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Authentication struct {
	Hash                 string   `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Time                 int64    `protobuf:"varint,3,opt,name=Time,proto3" json:"Time,omitempty"`
	Signature            string   `protobuf:"bytes,4,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Authentication) Reset()         { *m = Authentication{} }
func (m *Authentication) String() string { return proto.CompactTextString(m) }
func (*Authentication) ProtoMessage()    {}
func (*Authentication) Descriptor() ([]byte, []int) {
	return fileDescriptor_disgover_c7822d8cb2ad3fb3, []int{1}
}
func (m *Authentication) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Authentication.Unmarshal(m, b)
}
func (m *Authentication) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Authentication.Marshal(b, m, deterministic)
}
func (dst *Authentication) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Authentication.Merge(dst, src)
}
func (m *Authentication) XXX_Size() int {
	return xxx_messageInfo_Authentication.Size(m)
}
func (m *Authentication) XXX_DiscardUnknown() {
	xxx_messageInfo_Authentication.DiscardUnknown(m)
}

var xxx_messageInfo_Authentication proto.InternalMessageInfo

func (m *Authentication) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Authentication) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Authentication) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type Endpoint struct {
	Host                 string   `protobuf:"bytes,1,opt,name=Host,proto3" json:"Host,omitempty"`
	Port                 int64    `protobuf:"varint,2,opt,name=Port,proto3" json:"Port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Endpoint) Reset()         { *m = Endpoint{} }
func (m *Endpoint) String() string { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()    {}
func (*Endpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_disgover_c7822d8cb2ad3fb3, []int{2}
}
func (m *Endpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endpoint.Unmarshal(m, b)
}
func (m *Endpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endpoint.Marshal(b, m, deterministic)
}
func (dst *Endpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endpoint.Merge(dst, src)
}
func (m *Endpoint) XXX_Size() int {
	return xxx_messageInfo_Endpoint.Size(m)
}
func (m *Endpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Endpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Endpoint proto.InternalMessageInfo

func (m *Endpoint) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Endpoint) GetPort() int64 {
	if m != nil {
		return m.Port
	}
	return 0
}

type Node struct {
	Address              string    `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	GrpcEndpoint         *Endpoint `protobuf:"bytes,2,opt,name=GrpcEndpoint,proto3" json:"GrpcEndpoint,omitempty"`
	HttpEndpoint         *Endpoint `protobuf:"bytes,3,opt,name=HttpEndpoint,proto3" json:"HttpEndpoint,omitempty"`
	Type                 string    `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_disgover_c7822d8cb2ad3fb3, []int{3}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (dst *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(dst, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Node) GetGrpcEndpoint() *Endpoint {
	if m != nil {
		return m.GrpcEndpoint
	}
	return nil
}

func (m *Node) GetHttpEndpoint() *Endpoint {
	if m != nil {
		return m.HttpEndpoint
	}
	return nil
}

func (m *Node) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type PingSeed struct {
	Authentication       *Authentication `protobuf:"bytes,1,opt,name=Authentication,proto3" json:"Authentication,omitempty"`
	Node                 *Node           `protobuf:"bytes,2,opt,name=Node,proto3" json:"Node,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PingSeed) Reset()         { *m = PingSeed{} }
func (m *PingSeed) String() string { return proto.CompactTextString(m) }
func (*PingSeed) ProtoMessage()    {}
func (*PingSeed) Descriptor() ([]byte, []int) {
	return fileDescriptor_disgover_c7822d8cb2ad3fb3, []int{4}
}
func (m *PingSeed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingSeed.Unmarshal(m, b)
}
func (m *PingSeed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingSeed.Marshal(b, m, deterministic)
}
func (dst *PingSeed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingSeed.Merge(dst, src)
}
func (m *PingSeed) XXX_Size() int {
	return xxx_messageInfo_PingSeed.Size(m)
}
func (m *PingSeed) XXX_DiscardUnknown() {
	xxx_messageInfo_PingSeed.DiscardUnknown(m)
}

var xxx_messageInfo_PingSeed proto.InternalMessageInfo

func (m *PingSeed) GetAuthentication() *Authentication {
	if m != nil {
		return m.Authentication
	}
	return nil
}

func (m *PingSeed) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type Update struct {
	Authentication       *Authentication `protobuf:"bytes,1,opt,name=Authentication,proto3" json:"Authentication,omitempty"`
	Delegates            []*Node         `protobuf:"bytes,2,rep,name=Delegates,proto3" json:"Delegates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Update) Reset()         { *m = Update{} }
func (m *Update) String() string { return proto.CompactTextString(m) }
func (*Update) ProtoMessage()    {}
func (*Update) Descriptor() ([]byte, []int) {
	return fileDescriptor_disgover_c7822d8cb2ad3fb3, []int{5}
}
func (m *Update) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Update.Unmarshal(m, b)
}
func (m *Update) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Update.Marshal(b, m, deterministic)
}
func (dst *Update) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Update.Merge(dst, src)
}
func (m *Update) XXX_Size() int {
	return xxx_messageInfo_Update.Size(m)
}
func (m *Update) XXX_DiscardUnknown() {
	xxx_messageInfo_Update.DiscardUnknown(m)
}

var xxx_messageInfo_Update proto.InternalMessageInfo

func (m *Update) GetAuthentication() *Authentication {
	if m != nil {
		return m.Authentication
	}
	return nil
}

func (m *Update) GetDelegates() []*Node {
	if m != nil {
		return m.Delegates
	}
	return nil
}

type SoftwareUpdate struct {
	Authentication       *Authentication `protobuf:"bytes,1,opt,name=Authentication,proto3" json:"Authentication,omitempty"`
	Hash                 string          `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
	FileName             string          `protobuf:"bytes,3,opt,name=FileName,proto3" json:"FileName,omitempty"`
	Software             []byte          `protobuf:"bytes,4,opt,name=Software,proto3" json:"Software,omitempty"`
	Signature            string          `protobuf:"bytes,5,opt,name=Signature,proto3" json:"Signature,omitempty"`
	ScheduledReboot      string          `protobuf:"bytes,6,opt,name=ScheduledReboot,proto3" json:"ScheduledReboot,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SoftwareUpdate) Reset()         { *m = SoftwareUpdate{} }
func (m *SoftwareUpdate) String() string { return proto.CompactTextString(m) }
func (*SoftwareUpdate) ProtoMessage()    {}
func (*SoftwareUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_disgover_c7822d8cb2ad3fb3, []int{6}
}
func (m *SoftwareUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoftwareUpdate.Unmarshal(m, b)
}
func (m *SoftwareUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoftwareUpdate.Marshal(b, m, deterministic)
}
func (dst *SoftwareUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoftwareUpdate.Merge(dst, src)
}
func (m *SoftwareUpdate) XXX_Size() int {
	return xxx_messageInfo_SoftwareUpdate.Size(m)
}
func (m *SoftwareUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_SoftwareUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_SoftwareUpdate proto.InternalMessageInfo

func (m *SoftwareUpdate) GetAuthentication() *Authentication {
	if m != nil {
		return m.Authentication
	}
	return nil
}

func (m *SoftwareUpdate) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *SoftwareUpdate) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *SoftwareUpdate) GetSoftware() []byte {
	if m != nil {
		return m.Software
	}
	return nil
}

func (m *SoftwareUpdate) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *SoftwareUpdate) GetScheduledReboot() string {
	if m != nil {
		return m.ScheduledReboot
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "disgover.Empty")
	proto.RegisterType((*Authentication)(nil), "disgover.Authentication")
	proto.RegisterType((*Endpoint)(nil), "disgover.Endpoint")
	proto.RegisterType((*Node)(nil), "disgover.Node")
	proto.RegisterType((*PingSeed)(nil), "disgover.PingSeed")
	proto.RegisterType((*Update)(nil), "disgover.Update")
	proto.RegisterType((*SoftwareUpdate)(nil), "disgover.SoftwareUpdate")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DisgoverGrpcClient is the client API for DisgoverGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DisgoverGrpcClient interface {
	PingSeedGrpc(ctx context.Context, in *PingSeed, opts ...grpc.CallOption) (*Update, error)
	UpdateGrpc(ctx context.Context, in *Update, opts ...grpc.CallOption) (*Empty, error)
	UpdateSoftwareGrpc(ctx context.Context, in *SoftwareUpdate, opts ...grpc.CallOption) (*Empty, error)
}

type disgoverGrpcClient struct {
	cc *grpc.ClientConn
}

func NewDisgoverGrpcClient(cc *grpc.ClientConn) DisgoverGrpcClient {
	return &disgoverGrpcClient{cc}
}

func (c *disgoverGrpcClient) PingSeedGrpc(ctx context.Context, in *PingSeed, opts ...grpc.CallOption) (*Update, error) {
	out := new(Update)
	err := c.cc.Invoke(ctx, "/disgover.DisgoverGrpc/PingSeedGrpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *disgoverGrpcClient) UpdateGrpc(ctx context.Context, in *Update, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/disgover.DisgoverGrpc/UpdateGrpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *disgoverGrpcClient) UpdateSoftwareGrpc(ctx context.Context, in *SoftwareUpdate, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/disgover.DisgoverGrpc/UpdateSoftwareGrpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DisgoverGrpcServer is the server API for DisgoverGrpc service.
type DisgoverGrpcServer interface {
	PingSeedGrpc(context.Context, *PingSeed) (*Update, error)
	UpdateGrpc(context.Context, *Update) (*Empty, error)
	UpdateSoftwareGrpc(context.Context, *SoftwareUpdate) (*Empty, error)
}

func RegisterDisgoverGrpcServer(s *grpc.Server, srv DisgoverGrpcServer) {
	s.RegisterService(&_DisgoverGrpc_serviceDesc, srv)
}

func _DisgoverGrpc_PingSeedGrpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingSeed)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisgoverGrpcServer).PingSeedGrpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/disgover.DisgoverGrpc/PingSeedGrpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisgoverGrpcServer).PingSeedGrpc(ctx, req.(*PingSeed))
	}
	return interceptor(ctx, in, info, handler)
}

func _DisgoverGrpc_UpdateGrpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Update)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisgoverGrpcServer).UpdateGrpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/disgover.DisgoverGrpc/UpdateGrpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisgoverGrpcServer).UpdateGrpc(ctx, req.(*Update))
	}
	return interceptor(ctx, in, info, handler)
}

func _DisgoverGrpc_UpdateSoftwareGrpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SoftwareUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisgoverGrpcServer).UpdateSoftwareGrpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/disgover.DisgoverGrpc/UpdateSoftwareGrpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisgoverGrpcServer).UpdateSoftwareGrpc(ctx, req.(*SoftwareUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

var _DisgoverGrpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "disgover.DisgoverGrpc",
	HandlerType: (*DisgoverGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PingSeedGrpc",
			Handler:    _DisgoverGrpc_PingSeedGrpc_Handler,
		},
		{
			MethodName: "UpdateGrpc",
			Handler:    _DisgoverGrpc_UpdateGrpc_Handler,
		},
		{
			MethodName: "UpdateSoftwareGrpc",
			Handler:    _DisgoverGrpc_UpdateSoftwareGrpc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "disgover.proto",
}

func init() { proto.RegisterFile("disgover.proto", fileDescriptor_disgover_c7822d8cb2ad3fb3) }

var fileDescriptor_disgover_c7822d8cb2ad3fb3 = []byte{
	// 419 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xae, 0xeb, 0x34, 0x4d, 0xa6, 0x91, 0x8b, 0xf6, 0xb4, 0x8a, 0x38, 0x44, 0x7b, 0xca, 0x01,
	0x55, 0xc2, 0x48, 0x9c, 0x89, 0xd4, 0x42, 0x4f, 0x55, 0xb5, 0x06, 0xee, 0x6e, 0x76, 0x70, 0x56,
	0x4a, 0xbd, 0x2b, 0x7b, 0x03, 0xf4, 0x7d, 0x78, 0x0c, 0x9e, 0x87, 0xe7, 0x40, 0x1e, 0x7b, 0xfd,
	0x47, 0xb8, 0xe5, 0x36, 0xf3, 0xcd, 0x7c, 0xb3, 0xf3, 0xf3, 0x2d, 0x44, 0x4a, 0x97, 0x99, 0xf9,
	0x8e, 0xc5, 0x8d, 0x2d, 0x8c, 0x33, 0x6c, 0xe6, 0x7d, 0x71, 0x09, 0x17, 0x77, 0xcf, 0xd6, 0xbd,
	0x88, 0xaf, 0x10, 0x6d, 0x0e, 0x6e, 0x87, 0xb9, 0xd3, 0xdb, 0xd4, 0x69, 0x93, 0x33, 0x06, 0x93,
	0xfb, 0xb4, 0xdc, 0xf1, 0xf3, 0x55, 0xb0, 0x9e, 0x4b, 0xb2, 0x2b, 0xec, 0xb3, 0x7e, 0x46, 0x1e,
	0xae, 0x82, 0x75, 0x28, 0xc9, 0x66, 0xaf, 0x61, 0x9e, 0xe8, 0x2c, 0x4f, 0xdd, 0xa1, 0x40, 0x3e,
	0xa1, 0xe4, 0x0e, 0x10, 0x31, 0xcc, 0xee, 0x72, 0x65, 0x8d, 0xce, 0x1d, 0x55, 0x34, 0xa5, 0xe3,
	0x41, 0x53, 0xd1, 0x94, 0x84, 0x3d, 0x9a, 0xc2, 0xd1, 0x2b, 0xa1, 0x24, 0x5b, 0xfc, 0x0a, 0x60,
	0xf2, 0x60, 0x14, 0x32, 0x0e, 0x97, 0x1b, 0xa5, 0x0a, 0x2c, 0xcb, 0x86, 0xe3, 0x5d, 0xf6, 0x1e,
	0x16, 0x9f, 0x0a, 0xbb, 0xf5, 0xa5, 0x89, 0x7e, 0x15, 0xb3, 0x9b, 0x76, 0x50, 0x1f, 0x91, 0x83,
	0xbc, 0x8a, 0x77, 0xef, 0x9c, 0x6d, 0x79, 0xe1, 0xff, 0x79, 0xfd, 0x3c, 0x1a, 0xfc, 0xc5, 0xfa,
	0xf9, 0xc8, 0x16, 0x16, 0x66, 0x8f, 0x3a, 0xcf, 0x12, 0x44, 0xc5, 0x3e, 0x8c, 0xd7, 0x47, 0x0d,
	0x5f, 0xc5, 0xbc, 0xab, 0x3c, 0x8c, 0xcb, 0xf1, 0xba, 0x45, 0x3d, 0x73, 0x33, 0x49, 0xd4, 0xf1,
	0x2a, 0x54, 0x52, 0x4c, 0xfc, 0x84, 0xe9, 0x17, 0xab, 0x52, 0x87, 0x27, 0x78, 0xef, 0x0d, 0xcc,
	0x6f, 0x71, 0x8f, 0x59, 0xea, 0xb0, 0xe4, 0xe7, 0xab, 0xf0, 0xc8, 0xa3, 0x5d, 0x82, 0xf8, 0x13,
	0x40, 0x94, 0x98, 0x6f, 0xee, 0x47, 0x5a, 0xe0, 0xc9, 0x5a, 0x38, 0xa6, 0xb0, 0x25, 0xcc, 0x3e,
	0xea, 0x3d, 0x3e, 0xa4, 0x8d, 0xca, 0xe6, 0xb2, 0xf5, 0xab, 0x98, 0xef, 0x81, 0x0e, 0xb1, 0x90,
	0xad, 0x3f, 0x54, 0xe1, 0xc5, 0x48, 0x85, 0x6c, 0x0d, 0xd7, 0xc9, 0x76, 0x87, 0xea, 0xb0, 0x47,
	0x25, 0xf1, 0xc9, 0x18, 0xc7, 0xa7, 0x94, 0x33, 0x86, 0xe3, 0xdf, 0x01, 0x2c, 0x6e, 0x9b, 0xfe,
	0x2b, 0xe5, 0x54, 0x8a, 0xf1, 0x57, 0x26, 0xbf, 0xa7, 0x15, 0x8f, 0x2f, 0x5f, 0x75, 0x58, 0xbd,
	0x1c, 0x71, 0xc6, 0xde, 0x02, 0xd4, 0x36, 0xb1, 0xfe, 0xc9, 0x58, 0x5e, 0xf7, 0x34, 0x47, 0x3f,
	0xf0, 0x8c, 0x6d, 0x80, 0xd5, 0x41, 0x3f, 0x15, 0x51, 0x7b, 0xfb, 0x1c, 0x5e, 0xe0, 0x48, 0x89,
	0xa7, 0x29, 0x7d, 0xf0, 0x77, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x96, 0xdd, 0xc7, 0xdd, 0xf2,
	0x03, 0x00, 0x00,
}
