// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dapos.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_dapos_5bfaac72e55698b4, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Request struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload              string   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_dapos_5bfaac72e55698b4, []int{1}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Request) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type Response struct {
	Payload              string   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_dapos_5bfaac72e55698b4, []int{2}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type Item struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_dapos_5bfaac72e55698b4, []int{3}
}
func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (dst *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(dst, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Item) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SynchronizeRequest struct {
	Index                int64    `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SynchronizeRequest) Reset()         { *m = SynchronizeRequest{} }
func (m *SynchronizeRequest) String() string { return proto.CompactTextString(m) }
func (*SynchronizeRequest) ProtoMessage()    {}
func (*SynchronizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dapos_5bfaac72e55698b4, []int{4}
}
func (m *SynchronizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SynchronizeRequest.Unmarshal(m, b)
}
func (m *SynchronizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SynchronizeRequest.Marshal(b, m, deterministic)
}
func (dst *SynchronizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SynchronizeRequest.Merge(dst, src)
}
func (m *SynchronizeRequest) XXX_Size() int {
	return xxx_messageInfo_SynchronizeRequest.Size(m)
}
func (m *SynchronizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SynchronizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SynchronizeRequest proto.InternalMessageInfo

func (m *SynchronizeRequest) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type SynchronizeResponse struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SynchronizeResponse) Reset()         { *m = SynchronizeResponse{} }
func (m *SynchronizeResponse) String() string { return proto.CompactTextString(m) }
func (*SynchronizeResponse) ProtoMessage()    {}
func (*SynchronizeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dapos_5bfaac72e55698b4, []int{5}
}
func (m *SynchronizeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SynchronizeResponse.Unmarshal(m, b)
}
func (m *SynchronizeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SynchronizeResponse.Marshal(b, m, deterministic)
}
func (dst *SynchronizeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SynchronizeResponse.Merge(dst, src)
}
func (m *SynchronizeResponse) XXX_Size() int {
	return xxx_messageInfo_SynchronizeResponse.Size(m)
}
func (m *SynchronizeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SynchronizeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SynchronizeResponse proto.InternalMessageInfo

func (m *SynchronizeResponse) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "proto.Empty")
	proto.RegisterType((*Request)(nil), "proto.Request")
	proto.RegisterType((*Response)(nil), "proto.Response")
	proto.RegisterType((*Item)(nil), "proto.Item")
	proto.RegisterType((*SynchronizeRequest)(nil), "proto.SynchronizeRequest")
	proto.RegisterType((*SynchronizeResponse)(nil), "proto.SynchronizeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DAPoSGrpcClient is the client API for DAPoSGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DAPoSGrpcClient interface {
	SynchronizeGrpc(ctx context.Context, in *SynchronizeRequest, opts ...grpc.CallOption) (*SynchronizeResponse, error)
	GossipGrpc(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type dAPoSGrpcClient struct {
	cc *grpc.ClientConn
}

func NewDAPoSGrpcClient(cc *grpc.ClientConn) DAPoSGrpcClient {
	return &dAPoSGrpcClient{cc}
}

func (c *dAPoSGrpcClient) SynchronizeGrpc(ctx context.Context, in *SynchronizeRequest, opts ...grpc.CallOption) (*SynchronizeResponse, error) {
	out := new(SynchronizeResponse)
	err := c.cc.Invoke(ctx, "/proto.DAPoSGrpc/SynchronizeGrpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAPoSGrpcClient) GossipGrpc(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.DAPoSGrpc/GossipGrpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DAPoSGrpcServer is the server API for DAPoSGrpc service.
type DAPoSGrpcServer interface {
	SynchronizeGrpc(context.Context, *SynchronizeRequest) (*SynchronizeResponse, error)
	GossipGrpc(context.Context, *Request) (*Response, error)
}

func RegisterDAPoSGrpcServer(s *grpc.Server, srv DAPoSGrpcServer) {
	s.RegisterService(&_DAPoSGrpc_serviceDesc, srv)
}

func _DAPoSGrpc_SynchronizeGrpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SynchronizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAPoSGrpcServer).SynchronizeGrpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DAPoSGrpc/SynchronizeGrpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAPoSGrpcServer).SynchronizeGrpc(ctx, req.(*SynchronizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAPoSGrpc_GossipGrpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAPoSGrpcServer).GossipGrpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DAPoSGrpc/GossipGrpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAPoSGrpcServer).GossipGrpc(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _DAPoSGrpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DAPoSGrpc",
	HandlerType: (*DAPoSGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SynchronizeGrpc",
			Handler:    _DAPoSGrpc_SynchronizeGrpc_Handler,
		},
		{
			MethodName: "GossipGrpc",
			Handler:    _DAPoSGrpc_GossipGrpc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dapos.proto",
}

func init() { proto.RegisterFile("dapos.proto", fileDescriptor_dapos_5bfaac72e55698b4) }

var fileDescriptor_dapos_5bfaac72e55698b4 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x4f, 0xc1, 0x4e, 0xeb, 0x30,
	0x10, 0x7c, 0x7e, 0xa9, 0x09, 0xdd, 0x48, 0x14, 0x2d, 0x3d, 0x84, 0x9e, 0x8a, 0xc5, 0xa1, 0xe2,
	0x10, 0xa4, 0x72, 0x80, 0x2b, 0x12, 0xa8, 0x2a, 0x27, 0xe4, 0x7e, 0x41, 0x68, 0x56, 0xa2, 0xa2,
	0x8d, 0x4d, 0xec, 0x22, 0xcc, 0x17, 0xf0, 0xd9, 0x28, 0xb6, 0x83, 0x88, 0xe0, 0xe4, 0x9d, 0xd9,
	0x99, 0xd9, 0x31, 0x64, 0x55, 0xa9, 0x95, 0x29, 0x74, 0xa3, 0xac, 0x42, 0xee, 0x1f, 0x91, 0x02,
	0xbf, 0xdf, 0x69, 0xeb, 0xc4, 0x35, 0xa4, 0x92, 0x5e, 0xf7, 0x64, 0x2c, 0x22, 0x0c, 0xac, 0xd3,
	0x94, 0xb3, 0x29, 0x9b, 0x0d, 0xa5, 0x9f, 0x31, 0x87, 0x54, 0x97, 0x6e, 0xab, 0xca, 0x2a, 0xff,
	0xef, 0xe9, 0x0e, 0x8a, 0x73, 0x38, 0x94, 0x64, 0xb4, 0xaa, 0x4d, 0x4f, 0xc5, 0xfa, 0xaa, 0x02,
	0x06, 0x4b, 0x4b, 0x3b, 0x3c, 0x86, 0xe4, 0x85, 0x5c, 0xdc, 0xb6, 0x23, 0x8e, 0x81, 0xbf, 0x95,
	0xdb, 0x3d, 0xc5, 0xdc, 0x00, 0xc4, 0x05, 0xe0, 0xca, 0xd5, 0xeb, 0xe7, 0x46, 0xd5, 0x9b, 0x0f,
	0xea, 0x9a, 0x8d, 0x81, 0x2f, 0xeb, 0x8a, 0xde, 0xbd, 0x3f, 0x91, 0x01, 0x88, 0x1b, 0x38, 0xe9,
	0x69, 0x63, 0x99, 0x33, 0xe0, 0xed, 0x49, 0x93, 0xb3, 0x69, 0x32, 0xcb, 0xe6, 0x59, 0xf8, 0x78,
	0xd1, 0x72, 0x32, 0x6c, 0xe6, 0x9f, 0x0c, 0x86, 0x77, 0xb7, 0x8f, 0x6a, 0xb5, 0x68, 0xf4, 0x1a,
	0x1f, 0x60, 0xf4, 0x23, 0xc7, 0x53, 0xa7, 0xd1, 0xf4, 0xbb, 0xcb, 0x64, 0xf2, 0xd7, 0x2a, 0x9c,
	0x16, 0xff, 0xf0, 0x12, 0x60, 0xa1, 0x8c, 0xd9, 0x68, 0x1f, 0x73, 0x14, 0xb5, 0x9d, 0x77, 0xf4,
	0x8d, 0x3b, 0xc3, 0xd3, 0x81, 0x67, 0xae, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6d, 0x32, 0x65,
	0xf1, 0xa5, 0x01, 0x00, 0x00,
}
