// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/dapos.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_0530f8dac0ca745e, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Request struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload              string   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_0530f8dac0ca745e, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Request) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type Response struct {
	Payload              string   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_0530f8dac0ca745e, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type Item struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_0530f8dac0ca745e, []int{3}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Item) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Account struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Balance              string   `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`
	HertzAvailable       uint64   `protobuf:"varint,4,opt,name=hertzAvailable,proto3" json:"hertzAvailable,omitempty"`
	TransactionHash      string   `protobuf:"bytes,5,opt,name=transactionHash,proto3" json:"transactionHash,omitempty"`
	Created              int64    `protobuf:"varint,6,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,7,opt,name=updated,proto3" json:"updated,omitempty"`
	Nonce                uint64   `protobuf:"varint,8,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_0530f8dac0ca745e, []int{4}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *Account) GetHertzAvailable() uint64 {
	if m != nil {
		return m.HertzAvailable
	}
	return 0
}

func (m *Account) GetTransactionHash() string {
	if m != nil {
		return m.TransactionHash
	}
	return ""
}

func (m *Account) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Account) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *Account) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

type Transaction struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	From                 string   `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Value                int64    `protobuf:"varint,5,opt,name=value,proto3" json:"value,omitempty"`
	Code                 string   `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`
	Abi                  string   `protobuf:"bytes,7,opt,name=abi,proto3" json:"abi,omitempty"`
	Method               string   `protobuf:"bytes,8,opt,name=method,proto3" json:"method,omitempty"`
	Params               string   `protobuf:"bytes,9,opt,name=params,proto3" json:"params,omitempty"`
	Time                 int64    `protobuf:"varint,10,opt,name=time,proto3" json:"time,omitempty"`
	Signature            string   `protobuf:"bytes,11,opt,name=signature,proto3" json:"signature,omitempty"`
	Hertz                uint64   `protobuf:"varint,12,opt,name=hertz,proto3" json:"hertz,omitempty"`
	FromName             string   `protobuf:"bytes,13,opt,name=fromName,proto3" json:"fromName,omitempty"`
	ToName               string   `protobuf:"bytes,14,opt,name=toName,proto3" json:"toName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_0530f8dac0ca745e, []int{5}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Transaction) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Transaction) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Transaction) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Transaction) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Transaction) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Transaction) GetAbi() string {
	if m != nil {
		return m.Abi
	}
	return ""
}

func (m *Transaction) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Transaction) GetParams() string {
	if m != nil {
		return m.Params
	}
	return ""
}

func (m *Transaction) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Transaction) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Transaction) GetHertz() uint64 {
	if m != nil {
		return m.Hertz
	}
	return 0
}

func (m *Transaction) GetFromName() string {
	if m != nil {
		return m.FromName
	}
	return ""
}

func (m *Transaction) GetToName() string {
	if m != nil {
		return m.ToName
	}
	return ""
}

type Rumor struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	TransactionHash      string   `protobuf:"bytes,3,opt,name=transactionHash,proto3" json:"transactionHash,omitempty"`
	Time                 int64    `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	Signature            string   `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rumor) Reset()         { *m = Rumor{} }
func (m *Rumor) String() string { return proto.CompactTextString(m) }
func (*Rumor) ProtoMessage()    {}
func (*Rumor) Descriptor() ([]byte, []int) {
	return fileDescriptor_0530f8dac0ca745e, []int{6}
}

func (m *Rumor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rumor.Unmarshal(m, b)
}
func (m *Rumor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rumor.Marshal(b, m, deterministic)
}
func (m *Rumor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rumor.Merge(m, src)
}
func (m *Rumor) XXX_Size() int {
	return xxx_messageInfo_Rumor.Size(m)
}
func (m *Rumor) XXX_DiscardUnknown() {
	xxx_messageInfo_Rumor.DiscardUnknown(m)
}

var xxx_messageInfo_Rumor proto.InternalMessageInfo

func (m *Rumor) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Rumor) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Rumor) GetTransactionHash() string {
	if m != nil {
		return m.TransactionHash
	}
	return ""
}

func (m *Rumor) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Rumor) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type Gossip struct {
	TxHash               string   `protobuf:"bytes,1,opt,name=txHash,proto3" json:"txHash,omitempty"`
	Rumors               []*Rumor `protobuf:"bytes,2,rep,name=rumors,proto3" json:"rumors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Gossip) Reset()         { *m = Gossip{} }
func (m *Gossip) String() string { return proto.CompactTextString(m) }
func (*Gossip) ProtoMessage()    {}
func (*Gossip) Descriptor() ([]byte, []int) {
	return fileDescriptor_0530f8dac0ca745e, []int{7}
}

func (m *Gossip) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gossip.Unmarshal(m, b)
}
func (m *Gossip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gossip.Marshal(b, m, deterministic)
}
func (m *Gossip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gossip.Merge(m, src)
}
func (m *Gossip) XXX_Size() int {
	return xxx_messageInfo_Gossip.Size(m)
}
func (m *Gossip) XXX_DiscardUnknown() {
	xxx_messageInfo_Gossip.DiscardUnknown(m)
}

var xxx_messageInfo_Gossip proto.InternalMessageInfo

func (m *Gossip) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *Gossip) GetRumors() []*Rumor {
	if m != nil {
		return m.Rumors
	}
	return nil
}

type SynchronizeRequest struct {
	Index                int64    `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SynchronizeRequest) Reset()         { *m = SynchronizeRequest{} }
func (m *SynchronizeRequest) String() string { return proto.CompactTextString(m) }
func (*SynchronizeRequest) ProtoMessage()    {}
func (*SynchronizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0530f8dac0ca745e, []int{8}
}

func (m *SynchronizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SynchronizeRequest.Unmarshal(m, b)
}
func (m *SynchronizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SynchronizeRequest.Marshal(b, m, deterministic)
}
func (m *SynchronizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SynchronizeRequest.Merge(m, src)
}
func (m *SynchronizeRequest) XXX_Size() int {
	return xxx_messageInfo_SynchronizeRequest.Size(m)
}
func (m *SynchronizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SynchronizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SynchronizeRequest proto.InternalMessageInfo

func (m *SynchronizeRequest) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type SynchronizeResponse struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SynchronizeResponse) Reset()         { *m = SynchronizeResponse{} }
func (m *SynchronizeResponse) String() string { return proto.CompactTextString(m) }
func (*SynchronizeResponse) ProtoMessage()    {}
func (*SynchronizeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0530f8dac0ca745e, []int{9}
}

func (m *SynchronizeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SynchronizeResponse.Unmarshal(m, b)
}
func (m *SynchronizeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SynchronizeResponse.Marshal(b, m, deterministic)
}
func (m *SynchronizeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SynchronizeResponse.Merge(m, src)
}
func (m *SynchronizeResponse) XXX_Size() int {
	return xxx_messageInfo_SynchronizeResponse.Size(m)
}
func (m *SynchronizeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SynchronizeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SynchronizeResponse proto.InternalMessageInfo

func (m *SynchronizeResponse) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type SynchronizeAccountsResponse struct {
	Accounts             []*Account `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SynchronizeAccountsResponse) Reset()         { *m = SynchronizeAccountsResponse{} }
func (m *SynchronizeAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*SynchronizeAccountsResponse) ProtoMessage()    {}
func (*SynchronizeAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0530f8dac0ca745e, []int{10}
}

func (m *SynchronizeAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SynchronizeAccountsResponse.Unmarshal(m, b)
}
func (m *SynchronizeAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SynchronizeAccountsResponse.Marshal(b, m, deterministic)
}
func (m *SynchronizeAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SynchronizeAccountsResponse.Merge(m, src)
}
func (m *SynchronizeAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_SynchronizeAccountsResponse.Size(m)
}
func (m *SynchronizeAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SynchronizeAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SynchronizeAccountsResponse proto.InternalMessageInfo

func (m *SynchronizeAccountsResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type SynchronizeTransactionsResponse struct {
	Transactions         []*Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SynchronizeTransactionsResponse) Reset()         { *m = SynchronizeTransactionsResponse{} }
func (m *SynchronizeTransactionsResponse) String() string { return proto.CompactTextString(m) }
func (*SynchronizeTransactionsResponse) ProtoMessage()    {}
func (*SynchronizeTransactionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0530f8dac0ca745e, []int{11}
}

func (m *SynchronizeTransactionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SynchronizeTransactionsResponse.Unmarshal(m, b)
}
func (m *SynchronizeTransactionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SynchronizeTransactionsResponse.Marshal(b, m, deterministic)
}
func (m *SynchronizeTransactionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SynchronizeTransactionsResponse.Merge(m, src)
}
func (m *SynchronizeTransactionsResponse) XXX_Size() int {
	return xxx_messageInfo_SynchronizeTransactionsResponse.Size(m)
}
func (m *SynchronizeTransactionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SynchronizeTransactionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SynchronizeTransactionsResponse proto.InternalMessageInfo

func (m *SynchronizeTransactionsResponse) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type SynchronizeGossipResponse struct {
	Gossips              []*Gossip `protobuf:"bytes,1,rep,name=gossips,proto3" json:"gossips,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SynchronizeGossipResponse) Reset()         { *m = SynchronizeGossipResponse{} }
func (m *SynchronizeGossipResponse) String() string { return proto.CompactTextString(m) }
func (*SynchronizeGossipResponse) ProtoMessage()    {}
func (*SynchronizeGossipResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0530f8dac0ca745e, []int{12}
}

func (m *SynchronizeGossipResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SynchronizeGossipResponse.Unmarshal(m, b)
}
func (m *SynchronizeGossipResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SynchronizeGossipResponse.Marshal(b, m, deterministic)
}
func (m *SynchronizeGossipResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SynchronizeGossipResponse.Merge(m, src)
}
func (m *SynchronizeGossipResponse) XXX_Size() int {
	return xxx_messageInfo_SynchronizeGossipResponse.Size(m)
}
func (m *SynchronizeGossipResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SynchronizeGossipResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SynchronizeGossipResponse proto.InternalMessageInfo

func (m *SynchronizeGossipResponse) GetGossips() []*Gossip {
	if m != nil {
		return m.Gossips
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "proto.Empty")
	proto.RegisterType((*Request)(nil), "proto.Request")
	proto.RegisterType((*Response)(nil), "proto.Response")
	proto.RegisterType((*Item)(nil), "proto.Item")
	proto.RegisterType((*Account)(nil), "proto.Account")
	proto.RegisterType((*Transaction)(nil), "proto.Transaction")
	proto.RegisterType((*Rumor)(nil), "proto.Rumor")
	proto.RegisterType((*Gossip)(nil), "proto.Gossip")
	proto.RegisterType((*SynchronizeRequest)(nil), "proto.SynchronizeRequest")
	proto.RegisterType((*SynchronizeResponse)(nil), "proto.SynchronizeResponse")
	proto.RegisterType((*SynchronizeAccountsResponse)(nil), "proto.SynchronizeAccountsResponse")
	proto.RegisterType((*SynchronizeTransactionsResponse)(nil), "proto.SynchronizeTransactionsResponse")
	proto.RegisterType((*SynchronizeGossipResponse)(nil), "proto.SynchronizeGossipResponse")
}

func init() { proto.RegisterFile("proto/dapos.proto", fileDescriptor_0530f8dac0ca745e) }

var fileDescriptor_0530f8dac0ca745e = []byte{
	// 702 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x51, 0x6e, 0xd3, 0x4c,
	0x10, 0x8e, 0xe3, 0x38, 0x89, 0x27, 0x69, 0xfa, 0xff, 0x4b, 0x01, 0xb7, 0x20, 0x11, 0x56, 0x55,
	0x89, 0xfa, 0xd0, 0x4a, 0x45, 0x02, 0x5e, 0x2b, 0x15, 0xda, 0xf2, 0x80, 0xd0, 0x16, 0x21, 0xc1,
	0xdb, 0xc6, 0x5e, 0x1a, 0x8b, 0xd8, 0x6b, 0xec, 0x4d, 0xd5, 0xf4, 0x16, 0xdc, 0x80, 0xab, 0x70,
	0x20, 0xee, 0x80, 0x76, 0x76, 0x9d, 0xd8, 0x49, 0x50, 0x9f, 0x3c, 0xdf, 0xcc, 0xec, 0x37, 0xdf,
	0xcc, 0x78, 0xe0, 0xff, 0x2c, 0x97, 0x4a, 0x1e, 0x47, 0x3c, 0x93, 0xc5, 0x11, 0xda, 0xc4, 0xc3,
	0x0f, 0xed, 0x80, 0xf7, 0x36, 0xc9, 0xd4, 0x9c, 0xbe, 0x86, 0x0e, 0x13, 0x3f, 0x66, 0xa2, 0x50,
	0x84, 0x40, 0x4b, 0xcd, 0x33, 0x11, 0x38, 0x43, 0x67, 0xe4, 0x33, 0xb4, 0x49, 0x00, 0x9d, 0x8c,
	0xcf, 0xa7, 0x92, 0x47, 0x41, 0x13, 0xdd, 0x25, 0xa4, 0xfb, 0xd0, 0x65, 0xa2, 0xc8, 0x64, 0x5a,
	0xd4, 0xb2, 0x9c, 0x7a, 0xd6, 0x11, 0xb4, 0x2e, 0x95, 0x48, 0xc8, 0x7f, 0xe0, 0x7e, 0x17, 0x73,
	0x1b, 0xd5, 0x26, 0xd9, 0x01, 0xef, 0x86, 0x4f, 0x67, 0x02, 0x79, 0xfb, 0xcc, 0x00, 0xfa, 0xc7,
	0x81, 0xce, 0x69, 0x18, 0xca, 0x59, 0xaa, 0x34, 0x2b, 0x8f, 0xa2, 0x5c, 0x14, 0x45, 0xc9, 0x6a,
	0xa1, 0x56, 0x9a, 0xf2, 0x44, 0x58, 0x49, 0x68, 0xeb, 0xec, 0x31, 0x9f, 0xf2, 0x34, 0x14, 0x81,
	0x6b, 0xb2, 0x2d, 0x24, 0x07, 0x30, 0x98, 0x88, 0x5c, 0xdd, 0x9d, 0xde, 0xf0, 0x78, 0xca, 0xc7,
	0x53, 0x11, 0xb4, 0x86, 0xce, 0xa8, 0xc5, 0x56, 0xbc, 0x64, 0x04, 0xdb, 0x2a, 0xe7, 0x69, 0xc1,
	0x43, 0x15, 0xcb, 0xf4, 0x82, 0x17, 0x93, 0xc0, 0x43, 0xa6, 0x55, 0xb7, 0xae, 0x15, 0xe6, 0x82,
	0x2b, 0x11, 0x05, 0xed, 0xa1, 0x33, 0x72, 0x59, 0x09, 0x75, 0x64, 0x96, 0x45, 0x18, 0xe9, 0x98,
	0x88, 0x85, 0xba, 0xdf, 0x54, 0x6a, 0x75, 0x5d, 0x2c, 0x6e, 0x00, 0xfd, 0xdd, 0x84, 0xde, 0xa7,
	0x25, 0xbb, 0xee, 0x6c, 0xa2, 0x0b, 0xdb, 0x1d, 0x68, 0x7b, 0xb1, 0x17, 0xdd, 0xad, 0x67, 0xf7,
	0x42, 0xa0, 0xf5, 0x2d, 0x97, 0x89, 0x6d, 0x15, 0x6d, 0x32, 0x80, 0xa6, 0x92, 0xd8, 0x9b, 0xcf,
	0x9a, 0x4a, 0x2e, 0x27, 0xec, 0xa1, 0x12, 0x03, 0xf4, 0xcb, 0x50, 0x46, 0x02, 0x85, 0xfb, 0x0c,
	0x6d, 0xbd, 0x1d, 0x3e, 0x8e, 0x51, 0xb1, 0xcf, 0xb4, 0x49, 0x1e, 0x41, 0x3b, 0x11, 0x6a, 0x22,
	0x23, 0x94, 0xeb, 0x33, 0x8b, 0xb4, 0x3f, 0xe3, 0x39, 0x4f, 0x8a, 0xc0, 0x37, 0x7e, 0x83, 0x50,
	0x63, 0x9c, 0x88, 0x00, 0xb0, 0x14, 0xda, 0xe4, 0x29, 0xf8, 0x45, 0x7c, 0x9d, 0x72, 0x35, 0xcb,
	0x45, 0xd0, 0xc3, 0xf4, 0xa5, 0x43, 0xab, 0xc3, 0xf9, 0x07, 0x7d, 0x33, 0x0f, 0x04, 0x64, 0x0f,
	0xba, 0xba, 0x97, 0x0f, 0x7a, 0xbb, 0x5b, 0xf8, 0x64, 0x81, 0x75, 0x6d, 0x25, 0x31, 0x32, 0x30,
	0xb5, 0x0d, 0xa2, 0x3f, 0x1d, 0xf0, 0xd8, 0x2c, 0x91, 0xf9, 0xc6, 0xe9, 0x55, 0xfe, 0xa2, 0x66,
	0xfd, 0x2f, 0xda, 0xb0, 0x6f, 0x77, 0xf3, 0xbe, 0xcb, 0xee, 0x5a, 0xff, 0xea, 0xce, 0x5b, 0xe9,
	0x8e, 0xbe, 0x83, 0xf6, 0xb9, 0x2c, 0x8a, 0x38, 0x43, 0xd5, 0xb7, 0x17, 0x4b, 0x55, 0x16, 0x91,
	0x7d, 0x68, 0xe7, 0x5a, 0xb4, 0x96, 0xe5, 0x8e, 0x7a, 0x27, 0x7d, 0x73, 0xa0, 0x47, 0xd8, 0x09,
	0xb3, 0x31, 0x7a, 0x08, 0xe4, 0x6a, 0x9e, 0x86, 0x93, 0x5c, 0xa6, 0xf1, 0x9d, 0x28, 0x2f, 0x75,
	0x07, 0xbc, 0xcb, 0x34, 0x12, 0xb7, 0x48, 0xe9, 0x32, 0x03, 0xe8, 0x1b, 0x78, 0x50, 0xcb, 0xb5,
	0xc7, 0xf9, 0x1c, 0x3c, 0x7d, 0x82, 0xfa, 0x88, 0x74, 0x9d, 0x9e, 0xad, 0xa3, 0x7d, 0xcc, 0x44,
	0xe8, 0x25, 0x3c, 0xa9, 0xbc, 0xb4, 0xf7, 0x57, 0x2c, 0x18, 0x0e, 0xa1, 0xcb, 0xad, 0xcf, 0x92,
	0x0c, 0x2c, 0x89, 0x4d, 0x65, 0x8b, 0x38, 0xfd, 0x02, 0xcf, 0x2a, 0x54, 0x95, 0x5f, 0x7b, 0x49,
	0xf7, 0x0a, 0xfa, 0x95, 0x01, 0x97, 0x94, 0xc4, 0x52, 0x56, 0x9e, 0xb0, 0x5a, 0x1e, 0x3d, 0x83,
	0xdd, 0x0a, 0xb5, 0x19, 0xef, 0x82, 0xf4, 0x05, 0x74, 0xae, 0xd1, 0x53, 0xf2, 0x6d, 0x59, 0x3e,
	0x9b, 0x57, 0x46, 0x4f, 0x7e, 0xb9, 0xe0, 0x9f, 0x9d, 0x7e, 0x94, 0x57, 0xe7, 0x79, 0x16, 0x92,
	0xf7, 0xb0, 0x5d, 0xe5, 0xd4, 0xae, 0x5d, 0xfb, 0x70, 0x7d, 0xee, 0x7b, 0x7b, 0x9b, 0x42, 0x46,
	0x00, 0x6d, 0x90, 0xaf, 0xf0, 0x78, 0xc3, 0x14, 0xef, 0xe3, 0xa4, 0xeb, 0xa1, 0xd5, 0x05, 0xd0,
	0x06, 0x19, 0xd7, 0x36, 0x54, 0x1d, 0xeb, 0x7d, 0xfc, 0x07, 0xeb, 0xa1, 0x4d, 0x5b, 0xa1, 0x0d,
	0xf2, 0x19, 0x1e, 0xae, 0xcd, 0xf7, 0x3e, 0xf6, 0xe1, 0x7a, 0xa8, 0xbe, 0x18, 0xda, 0x20, 0xc7,
	0x00, 0x15, 0xb2, 0xf2, 0xd7, 0x29, 0x19, 0xb6, 0x17, 0xb8, 0x7c, 0x30, 0x6e, 0xa3, 0xe7, 0xe5,
	0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x53, 0xd7, 0x1e, 0x2e, 0xbf, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DAPoSGrpcClient is the client API for DAPoSGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DAPoSGrpcClient interface {
	SynchronizeGrpc(ctx context.Context, in *SynchronizeRequest, opts ...grpc.CallOption) (*SynchronizeResponse, error)
	SynchronizeAccountsGrpc(ctx context.Context, in *SynchronizeRequest, opts ...grpc.CallOption) (*SynchronizeAccountsResponse, error)
	SynchronizeTransactionsGrpc(ctx context.Context, in *SynchronizeRequest, opts ...grpc.CallOption) (*SynchronizeTransactionsResponse, error)
	SynchronizeGossipGrpc(ctx context.Context, in *SynchronizeRequest, opts ...grpc.CallOption) (*SynchronizeGossipResponse, error)
	GossipGrpc(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type dAPoSGrpcClient struct {
	cc *grpc.ClientConn
}

func NewDAPoSGrpcClient(cc *grpc.ClientConn) DAPoSGrpcClient {
	return &dAPoSGrpcClient{cc}
}

func (c *dAPoSGrpcClient) SynchronizeGrpc(ctx context.Context, in *SynchronizeRequest, opts ...grpc.CallOption) (*SynchronizeResponse, error) {
	out := new(SynchronizeResponse)
	err := c.cc.Invoke(ctx, "/proto.DAPoSGrpc/SynchronizeGrpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAPoSGrpcClient) SynchronizeAccountsGrpc(ctx context.Context, in *SynchronizeRequest, opts ...grpc.CallOption) (*SynchronizeAccountsResponse, error) {
	out := new(SynchronizeAccountsResponse)
	err := c.cc.Invoke(ctx, "/proto.DAPoSGrpc/SynchronizeAccountsGrpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAPoSGrpcClient) SynchronizeTransactionsGrpc(ctx context.Context, in *SynchronizeRequest, opts ...grpc.CallOption) (*SynchronizeTransactionsResponse, error) {
	out := new(SynchronizeTransactionsResponse)
	err := c.cc.Invoke(ctx, "/proto.DAPoSGrpc/SynchronizeTransactionsGrpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAPoSGrpcClient) SynchronizeGossipGrpc(ctx context.Context, in *SynchronizeRequest, opts ...grpc.CallOption) (*SynchronizeGossipResponse, error) {
	out := new(SynchronizeGossipResponse)
	err := c.cc.Invoke(ctx, "/proto.DAPoSGrpc/SynchronizeGossipGrpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAPoSGrpcClient) GossipGrpc(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.DAPoSGrpc/GossipGrpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DAPoSGrpcServer is the server API for DAPoSGrpc service.
type DAPoSGrpcServer interface {
	SynchronizeGrpc(context.Context, *SynchronizeRequest) (*SynchronizeResponse, error)
	SynchronizeAccountsGrpc(context.Context, *SynchronizeRequest) (*SynchronizeAccountsResponse, error)
	SynchronizeTransactionsGrpc(context.Context, *SynchronizeRequest) (*SynchronizeTransactionsResponse, error)
	SynchronizeGossipGrpc(context.Context, *SynchronizeRequest) (*SynchronizeGossipResponse, error)
	GossipGrpc(context.Context, *Request) (*Response, error)
}

func RegisterDAPoSGrpcServer(s *grpc.Server, srv DAPoSGrpcServer) {
	s.RegisterService(&_DAPoSGrpc_serviceDesc, srv)
}

func _DAPoSGrpc_SynchronizeGrpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SynchronizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAPoSGrpcServer).SynchronizeGrpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DAPoSGrpc/SynchronizeGrpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAPoSGrpcServer).SynchronizeGrpc(ctx, req.(*SynchronizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAPoSGrpc_SynchronizeAccountsGrpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SynchronizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAPoSGrpcServer).SynchronizeAccountsGrpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DAPoSGrpc/SynchronizeAccountsGrpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAPoSGrpcServer).SynchronizeAccountsGrpc(ctx, req.(*SynchronizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAPoSGrpc_SynchronizeTransactionsGrpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SynchronizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAPoSGrpcServer).SynchronizeTransactionsGrpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DAPoSGrpc/SynchronizeTransactionsGrpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAPoSGrpcServer).SynchronizeTransactionsGrpc(ctx, req.(*SynchronizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAPoSGrpc_SynchronizeGossipGrpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SynchronizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAPoSGrpcServer).SynchronizeGossipGrpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DAPoSGrpc/SynchronizeGossipGrpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAPoSGrpcServer).SynchronizeGossipGrpc(ctx, req.(*SynchronizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAPoSGrpc_GossipGrpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAPoSGrpcServer).GossipGrpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DAPoSGrpc/GossipGrpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAPoSGrpcServer).GossipGrpc(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _DAPoSGrpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DAPoSGrpc",
	HandlerType: (*DAPoSGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SynchronizeGrpc",
			Handler:    _DAPoSGrpc_SynchronizeGrpc_Handler,
		},
		{
			MethodName: "SynchronizeAccountsGrpc",
			Handler:    _DAPoSGrpc_SynchronizeAccountsGrpc_Handler,
		},
		{
			MethodName: "SynchronizeTransactionsGrpc",
			Handler:    _DAPoSGrpc_SynchronizeTransactionsGrpc_Handler,
		},
		{
			MethodName: "SynchronizeGossipGrpc",
			Handler:    _DAPoSGrpc_SynchronizeGossipGrpc_Handler,
		},
		{
			MethodName: "GossipGrpc",
			Handler:    _DAPoSGrpc_GossipGrpc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dapos.proto",
}
