// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/proto/disgo.proto

/*
Package services is a generated protocol buffer package.

It is generated from these files:
	grpc/proto/disgo.proto

It has these top-level messages:
	GetRequest
	SendResponse
*/
package services

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetRequest struct {
	Json string `protobuf:"bytes,1,opt,name=json" json:"json,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetRequest) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

type SendResponse struct {
	Json string `protobuf:"bytes,1,opt,name=json" json:"json,omitempty"`
}

func (m *SendResponse) Reset()                    { *m = SendResponse{} }
func (m *SendResponse) String() string            { return proto.CompactTextString(m) }
func (*SendResponse) ProtoMessage()               {}
func (*SendResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SendResponse) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "services.GetRequest")
	proto.RegisterType((*SendResponse)(nil), "services.SendResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DisgoGrpc service

type DisgoGrpcClient interface {
	Send(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*SendResponse, error)
}

type disgoGrpcClient struct {
	cc *grpc.ClientConn
}

func NewDisgoGrpcClient(cc *grpc.ClientConn) DisgoGrpcClient {
	return &disgoGrpcClient{cc}
}

func (c *disgoGrpcClient) Send(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	out := new(SendResponse)
	err := grpc.Invoke(ctx, "/services.DisgoGrpc/Send", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DisgoGrpc service

type DisgoGrpcServer interface {
	Send(context.Context, *GetRequest) (*SendResponse, error)
}

func RegisterDisgoGrpcServer(s *grpc.Server, srv DisgoGrpcServer) {
	s.RegisterService(&_DisgoGrpc_serviceDesc, srv)
}

func _DisgoGrpc_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisgoGrpcServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.DisgoGrpc/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisgoGrpcServer).Send(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DisgoGrpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.DisgoGrpc",
	HandlerType: (*DisgoGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _DisgoGrpc_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto/disgo.proto",
}

func init() { proto.RegisterFile("grpc/proto/disgo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0x2f, 0x2a, 0x48,
	0xd6, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0xc9, 0x2c, 0x4e, 0xcf, 0xd7, 0x03, 0xb3, 0x85,
	0x38, 0x8a, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x8b, 0x95, 0x14, 0xb8, 0xb8, 0xdc, 0x53, 0x4b,
	0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84, 0xb8, 0x58, 0xb2, 0x8a, 0xf3, 0xf3, 0x24,
	0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x25, 0x2e, 0x9e, 0xe0, 0xd4, 0xbc, 0x94,
	0xa0, 0xd4, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x6c, 0x6a, 0x8c, 0x9c, 0xb9, 0x38, 0x5d, 0x40,
	0xc6, 0xbb, 0x17, 0x15, 0x24, 0x0b, 0x99, 0x71, 0xb1, 0x80, 0x34, 0x08, 0x89, 0xe8, 0xc1, 0x6c,
	0xd1, 0x43, 0x58, 0x21, 0x25, 0x86, 0x10, 0x45, 0x36, 0x56, 0x89, 0x21, 0x89, 0x0d, 0xec, 0x36,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x19, 0xa0, 0xd2, 0x82, 0xb5, 0x00, 0x00, 0x00,
}
